### ISSUE TITLE
Unresolved references when I open Dnx.sln in VS

### ISSUE THREAD

**Issue by PradeepKadubandi** [aspnet/dnx#1457]
When you clone this repository and open it in VS, I see that Nuget.Versioning submodule is unable to resolved Microsoft.Framework.Runtime.Interfaces as a reference. See the image:

![submodules-globaljson](https://cloud.githubusercontent.com/assets/1424265/6761039/21867008-cf0c-11e4-8a4a-c17e5103a1dc.jpg)

Any idea why this is happening?

**Comment by davidfowl** [comment]
No project.lock.json?

**Comment by davidfowl** [comment]
@PradeepKadubandi @abpiskunov Why is it that dependencies are unresolved after opening? I thought we had logic that does a solution level restore (or per project) on projects with unresolved dependencies.

**Comment by abpiskunov** [comment]
I just debugged that and this issue should be resolved along with starting restore when project load completed. I will check it on Monday.

**Comment by davidfowl** [comment]
@abpiskunov Can you link to an issue here. I'm gonna close this out.

**Comment by abpiskunov** [comment]
Tracked now with this issue: https://github.com/aspnet/Tooling-Internal/issues/241

**Comment by eestein** [comment]
Any news on this error? I'm getting the same issue...

These are the versions I'm running for dnx and dnu:

```
SteinMac:BlackBeard eestein$ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64

SteinMac:BlackBeard eestein$ dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-16231
 Type:         CoreClr
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

I get a project.lock.json file but I still get unresolved dependencies:

```
SteinMac:BlackBeard eestein$ dnu list
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16231

Listing dependencies for BlackBeard (/Users/eestein/Documents/dev/tutos/blackbeard/BlackBeard/project.json)

[Target framework DNXCore,Version=v5.0 (dnxcore50)]

Unresolved references:
* Microsoft.AspNet.IISPlatformHandler 1.0.0-rc1-final - Unresolved
* Microsoft.AspNet.Mvc 6.0.0-rc1-final - Unresolved
* Microsoft.AspNet.Server.Kestrel 1.0.0-rc1-final - Unresolved
* Microsoft.AspNet.StaticFiles 1.0.0-rc1-final - Unresolved
* Microsoft.Extensions.Configuration.FileProviderExtensions 1.0.0-rc1-final - Unresolved
* Microsoft.Extensions.Logging 1.0.0-rc1-final - Unresolved
* Microsoft.Extensions.Logging.Console 1.0.0-rc1-final - Unresolved
* Microsoft.Extensions.Logging.Debug 1.0.0-rc1-final - Unresolved
```

I can't build =/

Thanks.
