### ISSUE TITLE
Wrapping a csproj: Getting an error for System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1'  

### ISSUE THREAD

**Issue by urigolani** [aspnet/dnx#1898]
(full error below)

## Setup:  
1. VS 2015 RC, freshly installed.
2. new solution with ASP vnext project under src and another classLibrary(old fashion)
3. asp references classLibrary (project json files for both, below)
4. a. publish to local folder succeeds but getting the above exception on run on web.cmd
4. b. if adding a nuget dependecy to classLibrary, which is reflected in the wrap project.json under the dependencies key, the publish itself from VS doesn't succeed due to an error such as:
c:\users\urig\documents\visual studio 2015\Projects\WebApplication4\wrap\ClassLibrary1\project.json(11,38): Error : Dependency Microsoft.Azure.DocumentDB >= 1.1.0 could not be resolved

### Notes: 
1. Upon successful publish (for 4.a) the classLibrary.dll along with nuget wrapper for v.1.0.0 is positioned correctly under approot/packages.
2. Modifying  wrap/ClassLibrary1/package.json which is generated automatically after using Add reference for the asp project. by replacing net451 with dnx451 solves the problem mentioned in the header. It creates an .nuspec which targets dnx4.5.1 and a dnx451 dir in the published approot/packages which was missing otherwise.
3. 4.b doesn't work no matter what, even after manually fixing dnx451 in the wrapper project.json VS is still unable to find the dependency to publish. To fix this I remove the dependency in the wrapped project.json so the publish works, and add it directly to the asp project.json

### asp project.json:
```
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-WebApplication4-8f619bc3-7e8b-4860-a684-c2d229502b5a",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta4",
    "EntityFramework.Commands": "7.0.0-beta4",
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta4",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta4",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta4",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta4",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta4",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta4",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta4",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.UserSecrets": "1.0.0-beta4",
    "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta4",
    "Microsoft.Framework.Logging": "1.0.0-beta4",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta4",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta4",
    "Newtonsoft.Json": "6.0.8",
    "Microsoft.Azure.DocumentDB": "1.1.0"

  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000",
    "gen": "Microsoft.Framework.CodeGeneration",
    "ef": "EntityFramework.Commands"
  },


  "frameworks": {
    "dnx451": {
      "dependencies": {
        "ClassLibrary1": "1.0.0-*"

      }
    },
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }
}
```

### classLibrary wrap project.json:
```
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "wrappedProject": "../../ClassLibrary2/ClassLibrary2.csproj",
      "bin": {
        "assembly": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.dll",
        "pdb": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.pdb"
      }
    },
    "net45": {
      "wrappedProject": "../../ClassLibrary2/ClassLibrary2.csproj",
      "bin": {
        "assembly": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.dll",
        "pdb": "../../ClassLibrary2/obj/{configuration}/ClassLibrary2.pdb"
      }
    }
  }
}
```
### Full error

note the nuspec line, I think that is what should be used to find the dlls.
.nuspec can be found below
```
C:\Microsoft\mAppStore>web.cmd
System.InvalidOperationException: Failed to resolve the following dependencies f
or target framework 'DNX,Version=v4.5.1':
   ClassLibrary1 1.0.0

Searched Locations:
  C:\Microsoft\mAppStore\approot\src\{name}\project.json
  C:\Microsoft\mAppStore\approot\test\{name}\project.json
  C:\Microsoft\mAppStore\approot\wrap\{name}\project.json
  C:\Microsoft\mAppStore\approot\packages\{name}\{version}\{name}.nuspec
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\
v4.5.1\{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\
v4.5.1\Facades\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationNa
me)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host,
String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)

C:\Microsoft\mAppStore>
```

### ClassLibrary.nuspec  (after publish, from approot/packages/.../)
```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ClassLibrary1</id>
    <version>1.0.0</version>
    <authors>ClassLibrary1</authors>
    <owners>ClassLibrary1</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>ClassLibrary1</description>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
  </metadata>
</package>
```

**Comment by davidfowl** [comment]
Where is the dnx version in all of this? Is it beta4? What's in the global.json

**Comment by urigolani** [comment]
beta4

global.json:
```
{
  "projects": [
    "src",
    "test",
    "wrap"
  ],
  "sdk": {
    "version": "1.0.0-beta4"
  }
}
```

**Comment by ChengTian** [comment]
Cannot reproduce with latest dnx. I believe this was fixed during @davidfowl 's `dnu publish` refactoring.

**Comment by urigolani** [comment]
When is beta5 due?

**Comment by ChengTian** [comment]
Hi @urigolani , to get latest runtime, you can do
```
dnvm upgrade -Unstable
```
which fetches latest beta5 runtime for you. Then change the sdk version in `global.json` to the version of latest runtime, for example
```
"sdk": {
    "version": "1.0.0-beta5-11893"
}
```

**Comment by urigolani** [comment]
Hi @ChengTian,

I've updated to 1.0.0-beta5-11976 and besides other issues with this version which are for a different thread, I still see the wrapping of referenced csproj files remains the same as it was with beta4

This means:
1. only net451 shows in the project.json of the wrapped project (in the wrap folder) missing dnx451.
2. If the csproj depends on nuget packages, then the following happens:
a. the project.json of the wrapped cs projhas a 'dependencies' property with the nuget package it depends on with the correct version.
b. the dependent package has a project.json in the 'wrap' folder, with a version of: 1.0.0.*

This means that If my csproj depends on Newtonsoft.json v6.0.8 then when the dnx tries build the project, it tries to resolve Newtonsoft.json to version 1.0.0

Can you try to repro and if this fails, contact me for further steps?

**Comment by ChengTian** [comment]
@urigolani 

1. It is expected because your csproj only targets net451. Wrapping a csproj cannot change its target framework.
2. Cannot reproduce. We should never create project.json for a NuGet package dependency. Can you open an new issue for this and share repro steps?
